"""initial tables

Revision ID: 40c0ea3f0ef7
Revises: 
Create Date: 2026-03-31 19:23:39.874330
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '40c0ea3f0ef7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
